# Generated by Django 6.0.4 on 2026-04-07 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Masculino, Femenino, Unisex', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Noir Elixir', max_length=150)),
                ('telefono_whatsapp', models.CharField(default='573000000000', help_text='Formato numérico sin símbolos. Ej: 573024445555', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('calidad', models.CharField(choices=[('Original', 'Original'), ('1.1', '1.1'), ('En Aceite', 'En Aceite')], default='Original', max_length=20)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumen_ml', models.IntegerField(help_text='Volumen en mililitros')),
                ('imagen', models.ImageField(upload_to='perfumes/')),
                ('en_promocion', models.BooleanField(default=False)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='catalogo.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='catalogo.marca')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='perfumes/extras/')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_extra', to='catalogo.perfume')),
            ],
        ),
    ]
